version: '3.5' 

services: 
  reverse-proxy:
    image: nginx:mainline-alpine-perl
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    restart: always

  redis-cache: 
    image: redis:alpine3.14
    ports:
      - 6379:6379
    restart: unless-stopped
    container_name: redis-cache

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    container_name: postgres_db
    volumes:
      - PGDBVol:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    restart: always
    environment:
      - ADMINER_DESIGN=galkaev
    depends_on:
      - db
    ports:
      - 7070:8080
    container_name: adminer

  frontend: 
    image: stack_frontend
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - 5000:5000
    container_name: frontend
    
  backend: 
    image: stack_backend
    build:
      context: .
      args:
        redis_host_param: redis-cache
        postgres_host_param: db
        postgres_user_param: postgres
        postgres_password_param: password
        postgres_database_param: postgres
      dockerfile: Dockerfile-Backend
    ports:
      - 8090:8080
    container_name: backend

volumes:
  PGDBVol:
  files: