FROM alpine/git:latest as git
WORKDIR /app
RUN git clone https://github.com/docker-hy/material-applications.git
    #pwd &&\
    #echo -e "\n" &&\
    #ls -la

FROM golang:rc-alpine3.14
EXPOSE 8080
WORKDIR /app
COPY --from=git /app/material-applications/example-backend/ .

ARG redis_host_param
ARG postgres_host_param
ARG postgres_user_param
ARG postgres_password_param
ARG postgres_database_param
ARG allowed_origins

ENV REQUEST_ORIGIN=http://localhost:5000
ENV REQUEST_ORIGIN=$allowed_origins
ENV GIN_MODE=release
ENV REDIS_HOST=$redis_host_param
ENV POSTGRES_HOST=$postgres_host_param
ENV POSTGRES_USER=$postgres_user_param
ENV POSTGRES_PASSWORD=$postgres_password_param
ENV POSTGRES_DATABASE=$postgres_database_param

RUN adduser -S appuser
RUN chown appuser /app

USER appuser

RUN go build

CMD ./server
