FROM alpine/git:latest as git
WORKDIR /app
RUN git clone https://github.com/docker-hy/material-applications.git

FROM node:lts-alpine3.14 as builder
WORKDIR /usr/src/app
COPY --from=git /app/material-applications/example-frontend/ .
ARG backend_url
ENV REACT_APP_BACKEND_URL=$backend_url
RUN npm install && npm run build

FROM node:lts-alpine3.14
EXPOSE 5000
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/build .
RUN npm install -g serve && adduser -S appuser
USER appuser
CMD serve -s -l 5000

#docker build . -f Dockerfile-Frontend --build-arg backend_url=http://localhost:8080/api -t frontend